<?php

// ################## THIS IS A GENERATED FILE ##################
// #################### DO NOT EDIT DIRECTLY ####################

namespace TickTackk\DeveloperTools;

/**
 * Class FakeComposer
 *
 * @package TickTackk\DeveloperTools
 */
class FakeComposer
{
    /**
     * @return array
     */
    protected static function getNamespaces()
    {
        /** @noinspection PhpTraditionalSyntaxArrayLiteralInspection */
        return array (
  'Prophecy\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/phpspec/prophecy/src',
  ),
);
    }

    /**
     * @return array
     */
    protected static function getPsr4()
    {
        /** @noinspection PhpTraditionalSyntaxArrayLiteralInspection */
        return array (
  'Bit3\\GitPhp\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/bit3/git-php/src',
  ),
  'Bit3\\GitPhp\\Test\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/bit3/git-php/tests',
  ),
  'Doctrine\\Instantiator\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/doctrine/instantiator/src/Doctrine/Instantiator',
  ),
  'DeepCopy\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/myclabs/deep-copy/src/DeepCopy',
  ),
  'phpDocumentor\\Reflection\\' => 
  array (
    0 => 'src/addons/TickTackk/DeveloperTools/vendor/phpdocumentor/reflection-common/src',
    1 => 'src/addons/TickTackk/DeveloperTools/vendor/phpdocumentor/reflection-docblock/src',
    2 => 'src/addons/TickTackk/DeveloperTools/vendor/phpdocumentor/type-resolver/src',
  ),
);
    }

    /**
     * @return array
     */
    protected static function getClassMap()
    {
        /** @noinspection PhpTraditionalSyntaxArrayLiteralInspection */
        return array (
  'PharIo\\Manifest\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\Exception.php',
  'PharIo\\Manifest\\InvalidApplicationNameException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\InvalidApplicationNameException.php',
  'PharIo\\Manifest\\InvalidEmailException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\InvalidEmailException.php',
  'PharIo\\Manifest\\InvalidUrlException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\InvalidUrlException.php',
  'PharIo\\Manifest\\ManifestDocumentException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\ManifestDocumentException.php',
  'PharIo\\Manifest\\ManifestDocumentMapperException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\ManifestDocumentMapperException.php',
  'PharIo\\Manifest\\ManifestElementException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\ManifestElementException.php',
  'PharIo\\Manifest\\ManifestLoaderException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\exceptions\\ManifestLoaderException.php',
  'PharIo\\Manifest\\ManifestDocumentMapper' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\ManifestDocumentMapper.php',
  'PharIo\\Manifest\\ManifestLoader' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\ManifestLoader.php',
  'PharIo\\Manifest\\ManifestSerializer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\ManifestSerializer.php',
  'PharIo\\Manifest\\Application' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Application.php',
  'PharIo\\Manifest\\ApplicationName' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\ApplicationName.php',
  'PharIo\\Manifest\\Author' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Author.php',
  'PharIo\\Manifest\\AuthorCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\AuthorCollection.php',
  'PharIo\\Manifest\\AuthorCollectionIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\AuthorCollectionIterator.php',
  'PharIo\\Manifest\\BundledComponent' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\BundledComponent.php',
  'PharIo\\Manifest\\BundledComponentCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\BundledComponentCollection.php',
  'PharIo\\Manifest\\BundledComponentCollectionIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\BundledComponentCollectionIterator.php',
  'PharIo\\Manifest\\CopyrightInformation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\CopyrightInformation.php',
  'PharIo\\Manifest\\Email' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Email.php',
  'PharIo\\Manifest\\Extension' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Extension.php',
  'PharIo\\Manifest\\Library' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Library.php',
  'PharIo\\Manifest\\License' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\License.php',
  'PharIo\\Manifest\\Manifest' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Manifest.php',
  'PharIo\\Manifest\\PhpExtensionRequirement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\PhpExtensionRequirement.php',
  'PharIo\\Manifest\\PhpVersionRequirement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\PhpVersionRequirement.php',
  'PharIo\\Manifest\\Requirement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Requirement.php',
  'PharIo\\Manifest\\RequirementCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\RequirementCollection.php',
  'PharIo\\Manifest\\RequirementCollectionIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\RequirementCollectionIterator.php',
  'PharIo\\Manifest\\Type' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Type.php',
  'PharIo\\Manifest\\Url' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\values\\Url.php',
  'PharIo\\Manifest\\AuthorElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\AuthorElement.php',
  'PharIo\\Manifest\\AuthorElementCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\AuthorElementCollection.php',
  'PharIo\\Manifest\\BundlesElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\BundlesElement.php',
  'PharIo\\Manifest\\ComponentElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ComponentElement.php',
  'PharIo\\Manifest\\ComponentElementCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ComponentElementCollection.php',
  'PharIo\\Manifest\\ContainsElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ContainsElement.php',
  'PharIo\\Manifest\\CopyrightElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\CopyrightElement.php',
  'PharIo\\Manifest\\ElementCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ElementCollection.php',
  'PharIo\\Manifest\\ExtElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ExtElement.php',
  'PharIo\\Manifest\\ExtElementCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ExtElementCollection.php',
  'PharIo\\Manifest\\ExtensionElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ExtensionElement.php',
  'PharIo\\Manifest\\LicenseElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\LicenseElement.php',
  'PharIo\\Manifest\\ManifestDocument' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ManifestDocument.php',
  'PharIo\\Manifest\\ManifestDocumentLoadingException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ManifestDocumentLoadingException.php',
  'PharIo\\Manifest\\ManifestElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\ManifestElement.php',
  'PharIo\\Manifest\\PhpElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\PhpElement.php',
  'PharIo\\Manifest\\RequiresElement' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/manifest\\src\\xml\\RequiresElement.php',
  'PharIo\\Version\\AbstractVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\AbstractVersionConstraint.php',
  'PharIo\\Version\\AndVersionConstraintGroup' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\AndVersionConstraintGroup.php',
  'PharIo\\Version\\AnyVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\AnyVersionConstraint.php',
  'PharIo\\Version\\ExactVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\ExactVersionConstraint.php',
  'PharIo\\Version\\GreaterThanOrEqualToVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\GreaterThanOrEqualToVersionConstraint.php',
  'PharIo\\Version\\OrVersionConstraintGroup' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\OrVersionConstraintGroup.php',
  'PharIo\\Version\\SpecificMajorAndMinorVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\SpecificMajorAndMinorVersionConstraint.php',
  'PharIo\\Version\\SpecificMajorVersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\SpecificMajorVersionConstraint.php',
  'PharIo\\Version\\VersionConstraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\constraints\\VersionConstraint.php',
  'PharIo\\Version\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\exceptions\\Exception.php',
  'PharIo\\Version\\InvalidPreReleaseSuffixException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\exceptions\\InvalidPreReleaseSuffixException.php',
  'PharIo\\Version\\InvalidVersionException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\exceptions\\InvalidVersionException.php',
  'PharIo\\Version\\UnsupportedVersionConstraintException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\exceptions\\UnsupportedVersionConstraintException.php',
  'PharIo\\Version\\PreReleaseSuffix' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\PreReleaseSuffix.php',
  'PharIo\\Version\\Version' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\Version.php',
  'PharIo\\Version\\VersionConstraintParser' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\VersionConstraintParser.php',
  'PharIo\\Version\\VersionConstraintValue' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\VersionConstraintValue.php',
  'PharIo\\Version\\VersionNumber' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phar-io/version\\src\\VersionNumber.php',
  'SebastianBergmann\\CodeCoverage\\CodeCoverage' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\CodeCoverage.php',
  'SebastianBergmann\\CodeCoverage\\Driver\\Driver' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Driver\\Driver.php',
  'SebastianBergmann\\CodeCoverage\\Driver\\PHPDBG' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Driver\\PHPDBG.php',
  'SebastianBergmann\\CodeCoverage\\Driver\\Xdebug' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Driver\\Xdebug.php',
  'SebastianBergmann\\CodeCoverage\\CoveredCodeNotExecutedException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\CoveredCodeNotExecutedException.php',
  'SebastianBergmann\\CodeCoverage\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\Exception.php',
  'SebastianBergmann\\CodeCoverage\\InvalidArgumentException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\InvalidArgumentException.php',
  'SebastianBergmann\\CodeCoverage\\MissingCoversAnnotationException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\MissingCoversAnnotationException.php',
  'SebastianBergmann\\CodeCoverage\\RuntimeException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\RuntimeException.php',
  'SebastianBergmann\\CodeCoverage\\UnintentionallyCoveredCodeException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Exception\\UnintentionallyCoveredCodeException.php',
  'SebastianBergmann\\CodeCoverage\\Filter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Filter.php',
  'SebastianBergmann\\CodeCoverage\\Node\\AbstractNode' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Node\\AbstractNode.php',
  'SebastianBergmann\\CodeCoverage\\Node\\Builder' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Node\\Builder.php',
  'SebastianBergmann\\CodeCoverage\\Node\\Directory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Node\\Directory.php',
  'SebastianBergmann\\CodeCoverage\\Node\\File' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Node\\File.php',
  'SebastianBergmann\\CodeCoverage\\Node\\Iterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Node\\Iterator.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Clover' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Clover.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Crap4j' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Crap4j.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Html\\Facade' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Html\\Facade.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Html\\Dashboard' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Html\\Renderer\\Dashboard.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Html\\Directory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Html\\Renderer\\Directory.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Html\\File' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Html\\Renderer\\File.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Html\\Renderer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Html\\Renderer.php',
  'SebastianBergmann\\CodeCoverage\\Report\\PHP' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\PHP.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Text' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Text.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\BuildInformation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\BuildInformation.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Coverage' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Coverage.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Directory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Directory.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Facade' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Facade.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\File' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\File.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Method' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Method.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Node' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Node.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Project' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Project.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Report' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Report.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Source' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Source.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Tests' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Tests.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Totals' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Totals.php',
  'SebastianBergmann\\CodeCoverage\\Report\\Xml\\Unit' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Report\\Xml\\Unit.php',
  'SebastianBergmann\\CodeCoverage\\Util' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Util.php',
  'SebastianBergmann\\CodeCoverage\\Version' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-code-coverage\\src\\Version.php',
  'SebastianBergmann\\FileIterator\\Facade' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-file-iterator\\src\\Facade.php',
  'SebastianBergmann\\FileIterator\\Factory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-file-iterator\\src\\Factory.php',
  'SebastianBergmann\\FileIterator\\Iterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-file-iterator\\src\\Iterator.php',
  'Text_Template' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-text-template\\src\\Template.php',
  'SebastianBergmann\\Timer\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-timer\\src\\Exception.php',
  'SebastianBergmann\\Timer\\RuntimeException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-timer\\src\\RuntimeException.php',
  'SebastianBergmann\\Timer\\Timer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-timer\\src\\Timer.php',
  'PHP_Token_Stream_CachingFactory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token\\Stream\\CachingFactory.php',
  'PHP_Token_Stream' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token\\Stream.php',
  'PHP_Token' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_TokenWithScope' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_TokenWithScopeAndVisibility' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_Includes' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FUNCTION' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INTERFACE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ABSTRACT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_AMPERSAND' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_AND_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ARRAY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ARRAY_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_AS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_AT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BACKTICK' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BAD_CHARACTER' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BOOLEAN_AND' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BOOLEAN_OR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BOOL_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_BREAK' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CARET' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CASE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CATCH' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CHARACTER' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLASS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLASS_C' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLASS_NAME_CONSTANT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLONE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLOSE_BRACKET' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLOSE_CURLY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLOSE_SQUARE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CLOSE_TAG' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_COLON' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_COMMA' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_COMMENT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CONCAT_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CONST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CONSTANT_ENCAPSED_STRING' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CONTINUE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CURLY_OPEN' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DEC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DECLARE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DEFAULT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DIV' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DIV_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DNUMBER' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DO' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOC_COMMENT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOLLAR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOLLAR_OPEN_CURLY_BRACES' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOUBLE_ARROW' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOUBLE_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOUBLE_COLON' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DOUBLE_QUOTES' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ECHO' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ELSE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ELSEIF' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EMPTY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENCAPSED_AND_WHITESPACE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDDECLARE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDFOR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDFOREACH' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDIF' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDSWITCH' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ENDWHILE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_END_HEREDOC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EVAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EXCLAMATION_MARK' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EXIT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_EXTENDS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FILE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FINAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FOR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FOREACH' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FUNC_C' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_GLOBAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_GT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IF' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IMPLEMENTS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INCLUDE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INCLUDE_ONCE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INLINE_HTML' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INSTANCEOF' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INT_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ISSET' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_GREATER_OR_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_IDENTICAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_NOT_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_NOT_IDENTICAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_IS_SMALLER_OR_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LINE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LIST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LNUMBER' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LOGICAL_AND' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LOGICAL_OR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LOGICAL_XOR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_LT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_METHOD_C' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_MINUS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_MINUS_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_MOD_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_MULT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_MUL_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_NEW' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_NUM_STRING' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OBJECT_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OBJECT_OPERATOR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OPEN_BRACKET' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OPEN_CURLY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OPEN_SQUARE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OPEN_TAG' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OPEN_TAG_WITH_ECHO' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_OR_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PAAMAYIM_NEKUDOTAYIM' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PERCENT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PIPE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PLUS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PLUS_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PRINT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PRIVATE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PROTECTED' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_PUBLIC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_QUESTION_MARK' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_REQUIRE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_REQUIRE_ONCE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_RETURN' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SEMICOLON' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SL_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SR_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_START_HEREDOC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_STATIC' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_STRING' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_STRING_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_STRING_VARNAME' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SWITCH' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_THROW' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_TILDE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_TRY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_UNSET' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_UNSET_CAST' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_USE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_USE_FUNCTION' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_VAR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_VARIABLE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_WHILE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_WHITESPACE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_XOR_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_HALT_COMPILER' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_DIR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_GOTO' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_NAMESPACE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_NS_C' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_NS_SEPARATOR' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_CALLABLE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_INSTEADOF' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_TRAIT' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_TRAIT_C' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_FINALLY' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_YIELD' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_ELLIPSIS' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_POW' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_POW_EQUAL' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_COALESCE' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_SPACESHIP' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'PHP_Token_YIELD_FROM' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\phpunit/php-token-stream\\src\\Token.php',
  'SebastianBergmann\\Comparator\\ArrayComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ArrayComparator.php',
  'SebastianBergmann\\Comparator\\Comparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\Comparator.php',
  'SebastianBergmann\\Comparator\\ComparisonFailure' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ComparisonFailure.php',
  'SebastianBergmann\\Comparator\\DateTimeComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\DateTimeComparator.php',
  'SebastianBergmann\\Comparator\\DOMNodeComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\DOMNodeComparator.php',
  'SebastianBergmann\\Comparator\\DoubleComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\DoubleComparator.php',
  'SebastianBergmann\\Comparator\\ExceptionComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ExceptionComparator.php',
  'SebastianBergmann\\Comparator\\Factory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\Factory.php',
  'SebastianBergmann\\Comparator\\MockObjectComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\MockObjectComparator.php',
  'SebastianBergmann\\Comparator\\NumericComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\NumericComparator.php',
  'SebastianBergmann\\Comparator\\ObjectComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ObjectComparator.php',
  'SebastianBergmann\\Comparator\\ResourceComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ResourceComparator.php',
  'SebastianBergmann\\Comparator\\ScalarComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\ScalarComparator.php',
  'SebastianBergmann\\Comparator\\SplObjectStorageComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\SplObjectStorageComparator.php',
  'SebastianBergmann\\Comparator\\TypeComparator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/comparator\\src\\TypeComparator.php',
  'SebastianBergmann\\Diff\\Chunk' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\Chunk.php',
  'SebastianBergmann\\Diff\\Diff' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\Diff.php',
  'SebastianBergmann\\Diff\\Differ' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\Differ.php',
  'SebastianBergmann\\Diff\\LCS\\LongestCommonSubsequence' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\LCS\\LongestCommonSubsequence.php',
  'SebastianBergmann\\Diff\\LCS\\MemoryEfficientImplementation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\LCS\\MemoryEfficientLongestCommonSubsequenceImplementation.php',
  'SebastianBergmann\\Diff\\LCS\\TimeEfficientImplementation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\LCS\\TimeEfficientLongestCommonSubsequenceImplementation.php',
  'SebastianBergmann\\Diff\\Line' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\Line.php',
  'SebastianBergmann\\Diff\\Parser' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/diff\\src\\Parser.php',
  'SebastianBergmann\\Environment\\Console' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/environment\\src\\Console.php',
  'SebastianBergmann\\Environment\\OperatingSystem' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/environment\\src\\OperatingSystem.php',
  'SebastianBergmann\\Environment\\Runtime' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/environment\\src\\Runtime.php',
  'SebastianBergmann\\Exporter\\Context' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/exporter\\src\\Context.php',
  'SebastianBergmann\\Exporter\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/exporter\\src\\Exception.php',
  'SebastianBergmann\\Exporter\\Exporter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/exporter\\src\\Exporter.php',
  'SebastianBergmann\\GlobalState\\Blacklist' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\Blacklist.php',
  'SebastianBergmann\\GlobalState\\CodeExporter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\CodeExporter.php',
  'SebastianBergmann\\GlobalState\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\exceptions\\Exception.php',
  'SebastianBergmann\\GlobalState\\RuntimeException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\exceptions\\RuntimeException.php',
  'SebastianBergmann\\GlobalState\\Restorer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\Restorer.php',
  'SebastianBergmann\\GlobalState\\Snapshot' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/global-state\\src\\Snapshot.php',
  'SebastianBergmann\\ObjectEnumerator\\Enumerator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/object-enumerator\\src\\Enumerator.php',
  'SebastianBergmann\\ObjectEnumerator\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/object-enumerator\\src\\Exception.php',
  'SebastianBergmann\\ObjectEnumerator\\InvalidArgumentException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/object-enumerator\\src\\InvalidArgumentException.php',
  'SebastianBergmann\\RecursionContext\\Context' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/recursion-context\\src\\Context.php',
  'SebastianBergmann\\RecursionContext\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/recursion-context\\src\\Exception.php',
  'SebastianBergmann\\RecursionContext\\InvalidArgumentException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/recursion-context\\src\\InvalidArgumentException.php',
  'SebastianBergmann\\ResourceOperations\\ResourceOperations' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/resource-operations\\src\\ResourceOperations.php',
  'SebastianBergmann\\Version' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastian/version\\src\\Version.php',
  'PHPUnit\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Exception.php',
  'PHPUnit\\Framework\\Assert' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Assert.php',
  'PHPUnit\\Framework\\AssertionFailedError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\AssertionFailedError.php',
  'PHPUnit\\Framework\\CodeCoverageException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\CodeCoverageException.php',
  'PHPUnit\\Framework\\Constraint\\ArrayHasKey' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ArrayHasKey.php',
  'PHPUnit\\Framework\\Constraint\\ArraySubset' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ArraySubset.php',
  'PHPUnit\\Framework\\Constraint\\Attribute' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Attribute.php',
  'PHPUnit\\Framework\\Constraint\\Callback' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Callback.php',
  'PHPUnit\\Framework\\Constraint\\ClassHasAttribute' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ClassHasAttribute.php',
  'PHPUnit\\Framework\\Constraint\\ClassHasStaticAttribute' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ClassHasStaticAttribute.php',
  'PHPUnit\\Framework\\Constraint\\Composite' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Composite.php',
  'PHPUnit\\Framework\\Constraint\\Constraint' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Constraint.php',
  'PHPUnit\\Framework\\Constraint\\Count' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Count.php',
  'PHPUnit\\Framework\\Constraint\\DirectoryExists' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\DirectoryExists.php',
  'PHPUnit\\Framework\\Constraint\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\Exception.php',
  'PHPUnit\\Framework\\Constraint\\ExceptionCode' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ExceptionCode.php',
  'PHPUnit\\Framework\\Constraint\\ExceptionMessage' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ExceptionMessage.php',
  'PHPUnit\\Framework\\Constraint\\ExceptionMessageRegularExpression' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ExceptionMessageRegularExpression.php',
  'PHPUnit\\Framework\\Constraint\\FileExists' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\FileExists.php',
  'PHPUnit\\Framework\\Constraint\\GreaterThan' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\GreaterThan.php',
  'PHPUnit\\Framework\\Constraint\\IsAnything' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsAnything.php',
  'PHPUnit\\Framework\\Constraint\\IsEmpty' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsEmpty.php',
  'PHPUnit\\Framework\\Constraint\\IsEqual' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsEqual.php',
  'PHPUnit\\Framework\\Constraint\\IsFalse' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsFalse.php',
  'PHPUnit\\Framework\\Constraint\\IsFinite' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsFinite.php',
  'PHPUnit\\Framework\\Constraint\\IsIdentical' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsIdentical.php',
  'PHPUnit\\Framework\\Constraint\\IsInfinite' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsInfinite.php',
  'PHPUnit\\Framework\\Constraint\\IsInstanceOf' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsInstanceOf.php',
  'PHPUnit\\Framework\\Constraint\\IsJson' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsJson.php',
  'PHPUnit\\Framework\\Constraint\\IsNan' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsNan.php',
  'PHPUnit\\Framework\\Constraint\\IsNull' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsNull.php',
  'PHPUnit\\Framework\\Constraint\\IsReadable' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsReadable.php',
  'PHPUnit\\Framework\\Constraint\\IsTrue' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsTrue.php',
  'PHPUnit\\Framework\\Constraint\\IsType' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsType.php',
  'PHPUnit\\Framework\\Constraint\\IsWritable' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\IsWritable.php',
  'PHPUnit\\Framework\\Constraint\\JsonMatches' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\JsonMatches.php',
  'PHPUnit\\Framework\\Constraint\\JsonMatchesErrorMessageProvider' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\JsonMatchesErrorMessageProvider.php',
  'PHPUnit\\Framework\\Constraint\\LessThan' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\LessThan.php',
  'PHPUnit\\Framework\\Constraint\\LogicalAnd' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\LogicalAnd.php',
  'PHPUnit\\Framework\\Constraint\\LogicalNot' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\LogicalNot.php',
  'PHPUnit\\Framework\\Constraint\\LogicalOr' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\LogicalOr.php',
  'PHPUnit\\Framework\\Constraint\\LogicalXor' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\LogicalXor.php',
  'PHPUnit\\Framework\\Constraint\\ObjectHasAttribute' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\ObjectHasAttribute.php',
  'PHPUnit\\Framework\\Constraint\\RegularExpression' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\RegularExpression.php',
  'PHPUnit\\Framework\\Constraint\\SameSize' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\SameSize.php',
  'PHPUnit\\Framework\\Constraint\\StringContains' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\StringContains.php',
  'PHPUnit\\Framework\\Constraint\\StringEndsWith' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\StringEndsWith.php',
  'PHPUnit\\Framework\\Constraint\\StringMatchesFormatDescription' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\StringMatchesFormatDescription.php',
  'PHPUnit\\Framework\\Constraint\\StringStartsWith' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\StringStartsWith.php',
  'PHPUnit\\Framework\\Constraint\\TraversableContains' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\TraversableContains.php',
  'PHPUnit\\Framework\\Constraint\\TraversableContainsOnly' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Constraint\\TraversableContainsOnly.php',
  'PHPUnit\\Framework\\CoveredCodeNotExecutedException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\CoveredCodeNotExecutedException.php',
  'PHPUnit\\Framework\\DataProviderTestSuite' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\DataProviderTestSuite.php',
  'PHPUnit\\Framework\\Error\\Deprecated' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Error\\Deprecated.php',
  'PHPUnit\\Framework\\Error\\Error' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Error\\Error.php',
  'PHPUnit\\Framework\\Error\\Notice' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Error\\Notice.php',
  'PHPUnit\\Framework\\Error\\Warning' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Error\\Warning.php',
  'PHPUnit\\Framework\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Exception.php',
  'PHPUnit\\Framework\\ExceptionWrapper' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\ExceptionWrapper.php',
  'PHPUnit\\Framework\\ExpectationFailedException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\ExpectationFailedException.php',
  'PHPUnit\\Framework\\IncompleteTest' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\IncompleteTest.php',
  'PHPUnit\\Framework\\IncompleteTestCase' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\IncompleteTestCase.php',
  'PHPUnit\\Framework\\IncompleteTestError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\IncompleteTestError.php',
  'PHPUnit\\Framework\\InvalidCoversTargetException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\InvalidCoversTargetException.php',
  'PHPUnit\\Framework\\MissingCoversAnnotationException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MissingCoversAnnotationException.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\Identity' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\Identity.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\InvocationMocker' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\InvocationMocker.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\Match' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\Match.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\MethodNameMatch' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\MethodNameMatch.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\NamespaceMatch' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\NamespaceMatch.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\ParametersMatch' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\ParametersMatch.php',
  'PHPUnit\\Framework\\MockObject\\Builder\\Stub' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Builder\\Stub.php',
  'PHPUnit\\Framework\\MockObject\\BadMethodCallException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Exception\\BadMethodCallException.php',
  'PHPUnit\\Framework\\MockObject\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Exception\\Exception.php',
  'PHPUnit\\Framework\\MockObject\\RuntimeException' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Exception\\RuntimeException.php',
  'PHPUnit\\Framework\\MockObject\\MockObject' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\ForwardCompatibility\\MockObject.php',
  'PHPUnit\\Framework\\MockObject\\Generator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Generator.php',
  'PHPUnit\\Framework\\MockObject\\Invocation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Invocation\\Invocation.php',
  'PHPUnit\\Framework\\MockObject\\Invocation\\ObjectInvocation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Invocation\\ObjectInvocation.php',
  'PHPUnit\\Framework\\MockObject\\Invocation\\StaticInvocation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Invocation\\StaticInvocation.php',
  'PHPUnit\\Framework\\MockObject\\InvocationMocker' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\InvocationMocker.php',
  'PHPUnit\\Framework\\MockObject\\Invokable' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Invokable.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\AnyInvokedCount' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\AnyInvokedCount.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\AnyParameters' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\AnyParameters.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\ConsecutiveParameters' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\ConsecutiveParameters.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\DeferredError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\DeferredError.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\Invocation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\Invocation.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedAtIndex' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedAtIndex.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedAtLeastCount' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedAtLeastCount.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedAtLeastOnce' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedAtLeastOnce.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedAtMostCount' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedAtMostCount.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedCount' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedCount.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\InvokedRecorder' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\InvokedRecorder.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\MethodName' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\MethodName.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\Parameters' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\Parameters.php',
  'PHPUnit\\Framework\\MockObject\\Matcher\\StatelessInvocation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher\\StatelessInvocation.php',
  'PHPUnit\\Framework\\MockObject\\Matcher' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Matcher.php',
  'PHPUnit\\Framework\\MockObject\\MockBuilder' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\MockBuilder.php',
  'PHPUnit_Framework_MockObject_MockObject' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\MockObject.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ConsecutiveCalls' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ConsecutiveCalls.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\Exception.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\MatcherCollection' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\MatcherCollection.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnArgument' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnArgument.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnCallback' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnCallback.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnReference' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnReference.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnSelf' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnSelf.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnStub' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnStub.php',
  'PHPUnit\\Framework\\MockObject\\Stub\\ReturnValueMap' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub\\ReturnValueMap.php',
  'PHPUnit\\Framework\\MockObject\\Stub' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Stub.php',
  'PHPUnit\\Framework\\MockObject\\Verifiable' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\MockObject\\Verifiable.php',
  'PHPUnit\\Framework\\OutputError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\OutputError.php',
  'PHPUnit\\Framework\\RiskyTest' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\RiskyTest.php',
  'PHPUnit\\Framework\\RiskyTestError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\RiskyTestError.php',
  'PHPUnit\\Framework\\SelfDescribing' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SelfDescribing.php',
  'PHPUnit\\Framework\\SkippedTest' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SkippedTest.php',
  'PHPUnit\\Framework\\SkippedTestCase' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SkippedTestCase.php',
  'PHPUnit\\Framework\\SkippedTestError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SkippedTestError.php',
  'PHPUnit\\Framework\\SkippedTestSuiteError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SkippedTestSuiteError.php',
  'PHPUnit\\Framework\\SyntheticError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\SyntheticError.php',
  'PHPUnit\\Framework\\Test' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Test.php',
  'PHPUnit\\Framework\\TestCase' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestCase.php',
  'PHPUnit\\Framework\\TestFailure' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestFailure.php',
  'PHPUnit\\Framework\\TestListener' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestListener.php',
  'PHPUnit\\Framework\\TestListenerDefaultImplementation' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestListenerDefaultImplementation.php',
  'PHPUnit\\Framework\\TestResult' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestResult.php',
  'PHPUnit\\Framework\\TestSuite' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestSuite.php',
  'PHPUnit\\Framework\\TestSuiteIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\TestSuiteIterator.php',
  'PHPUnit\\Framework\\UnintentionallyCoveredCodeError' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\UnintentionallyCoveredCodeError.php',
  'PHPUnit\\Framework\\Warning' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\Warning.php',
  'PHPUnit\\Framework\\WarningTestCase' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Framework\\WarningTestCase.php',
  'PHPUnit\\Runner\\BaseTestRunner' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\BaseTestRunner.php',
  'PHPUnit\\Runner\\Exception' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Exception.php',
  'PHPUnit\\Runner\\Filter\\ExcludeGroupFilterIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Filter\\ExcludeGroupFilterIterator.php',
  'PHPUnit\\Runner\\Filter\\Factory' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Filter\\Factory.php',
  'PHPUnit\\Runner\\Filter\\GroupFilterIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Filter\\GroupFilterIterator.php',
  'PHPUnit\\Runner\\Filter\\IncludeGroupFilterIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Filter\\IncludeGroupFilterIterator.php',
  'PHPUnit\\Runner\\Filter\\NameFilterIterator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Filter\\NameFilterIterator.php',
  'PHPUnit\\Runner\\AfterIncompleteTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterIncompleteTestHook.php',
  'PHPUnit\\Runner\\AfterLastTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterLastTestHook.php',
  'PHPUnit\\Runner\\AfterRiskyTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterRiskyTestHook.php',
  'PHPUnit\\Runner\\AfterSkippedTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterSkippedTestHook.php',
  'PHPUnit\\Runner\\AfterSuccessfulTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterSuccessfulTestHook.php',
  'PHPUnit\\Runner\\AfterTestErrorHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterTestErrorHook.php',
  'PHPUnit\\Runner\\AfterTestFailureHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterTestFailureHook.php',
  'PHPUnit\\Runner\\AfterTestWarningHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\AfterTestWarningHook.php',
  'PHPUnit\\Runner\\BeforeFirstTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\BeforeFirstTestHook.php',
  'PHPUnit\\Runner\\BeforeTestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\BeforeTestHook.php',
  'PHPUnit\\Runner\\Hook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\Hook.php',
  'PHPUnit\\Runner\\TestHook' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\TestHook.php',
  'PHPUnit\\Runner\\TestListenerAdapter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Hook\\TestListenerAdapter.php',
  'PHPUnit\\Runner\\PhptTestCase' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\PhptTestCase.php',
  'PHPUnit\\Runner\\ResultCacheExtension' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\ResultCacheExtension.php',
  'PHPUnit\\Runner\\StandardTestSuiteLoader' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\StandardTestSuiteLoader.php',
  'PHPUnit\\Runner\\TestSuiteLoader' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\TestSuiteLoader.php',
  'PHPUnit\\Runner\\TestSuiteSorter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\TestSuiteSorter.php',
  'PHPUnit\\Runner\\Version' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Runner\\Version.php',
  'PHPUnit\\TextUI\\Command' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\TextUI\\Command.php',
  'PHPUnit\\TextUI\\ResultPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\TextUI\\ResultPrinter.php',
  'PHPUnit\\TextUI\\TestRunner' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\TextUI\\TestRunner.php',
  'PHPUnit\\Util\\Blacklist' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Blacklist.php',
  'PHPUnit\\Util\\Configuration' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Configuration.php',
  'PHPUnit\\Util\\ConfigurationGenerator' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\ConfigurationGenerator.php',
  'PHPUnit\\Util\\ErrorHandler' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\ErrorHandler.php',
  'PHPUnit\\Util\\FileLoader' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\FileLoader.php',
  'PHPUnit\\Util\\Filesystem' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Filesystem.php',
  'PHPUnit\\Util\\Filter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Filter.php',
  'PHPUnit\\Util\\Getopt' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Getopt.php',
  'PHPUnit\\Util\\GlobalState' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\GlobalState.php',
  'PHPUnit\\Util\\InvalidArgumentHelper' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\InvalidArgumentHelper.php',
  'PHPUnit\\Util\\Json' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Json.php',
  'PHPUnit\\Util\\Log\\JUnit' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Log\\JUnit.php',
  'PHPUnit\\Util\\Log\\TeamCity' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Log\\TeamCity.php',
  'PHPUnit\\Runner\\NullTestResultCache' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\NullTestResultCache.php',
  'PHPUnit\\Util\\PHP\\AbstractPhpProcess' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\PHP\\AbstractPhpProcess.php',
  'PHPUnit\\Util\\PHP\\DefaultPhpProcess' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\PHP\\DefaultPhpProcess.php',
  'PHPUnit\\Util\\PHP\\WindowsPhpProcess' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\PHP\\WindowsPhpProcess.php',
  'PHPUnit\\Util\\Printer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Printer.php',
  'PHPUnit\\Util\\RegularExpression' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\RegularExpression.php',
  'PHPUnit\\Util\\Test' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Test.php',
  'PHPUnit\\Util\\TestDox\\CliTestDoxPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\CliTestDoxPrinter.php',
  'PHPUnit\\Util\\TestDox\\HtmlResultPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\HtmlResultPrinter.php',
  'PHPUnit\\Util\\TestDox\\NamePrettifier' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\NamePrettifier.php',
  'PHPUnit\\Util\\TestDox\\ResultPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\ResultPrinter.php',
  'PHPUnit\\Util\\TestDox\\TestResult' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\TestResult.php',
  'PHPUnit\\Util\\TestDox\\TextResultPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\TextResultPrinter.php',
  'PHPUnit\\Util\\TestDox\\XmlResultPrinter' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestDox\\XmlResultPrinter.php',
  'PHPUnit\\Runner\\TestResultCache' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestResultCache.php',
  'PHPUnit\\Runner\\TestResultCacheInterface' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TestResultCacheInterface.php',
  'PHPUnit\\Util\\TextTestListRenderer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\TextTestListRenderer.php',
  'PHPUnit\\Util\\Type' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Type.php',
  'PHPUnit\\Util\\Xml' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\Xml.php',
  'PHPUnit\\Util\\XmlTestListRenderer' => 'src\\addons\\TickTackk\\DeveloperTools\\vendor\\sebastianbergmann/phpunit\\src\\Util\\XmlTestListRenderer.php',
);
    }

    /**
     * @return array
     */
    protected static function getRequiredFiles()
    {
        /** @noinspection PhpTraditionalSyntaxArrayLiteralInspection */
        return array (
  0 => 'src/addons/TickTackk/DeveloperTools/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
);
    }
    
    /**
     * @param \XF\App $app
     */
    public static function appSetup(\XF\App $app)
    {
        foreach (self::getNamespaces() AS $namespace => $filePath)
        {
            \XF::$autoLoader->add($namespace, $filePath);
        }

        foreach (self::getPsr4() AS $namespace => $filePath)
        {
            \XF::$autoLoader->addPsr4($namespace, $filePath, true);
        }

        \XF::$autoLoader->addClassMap(self::getClassMap());

        foreach (self::getRequiredFiles() AS $filePath)
        {
            if (file_exists($filePath) && is_readable($filePath))
            {
                require $filePath;
            }
            else
            {
                throw new \InvalidArgumentException("{$filePath} does not exist.");
            }
        }
    }
}